public class Event{

public static final char DEATH = 'd';
public static final char MUTATION = 'm';
public static final char REPRODUCTION = 'r';
public Event[] event = new Event[3]; 
}

public Event(){

	this.event[0] = 
	this.event[1] =
	this.event[2] =

	public char type(char, double , Indiviual){
	
	return;
	
	}
    
	
	
	public double time(){
	
	return;
	
	}
    
	public Individual individual(){
	
	return;
	
	}
	
	public string toString(){

		switch(event){
			case'd': break;
			case'm': break;
			case 'r': break;
		}

	}

}